/* Estado Maior V25 — central estratégica prioritária e governo narrativo. */
(function(){
  document.body.classList.add('v25-government-events');
  const $id=id=>document.getElementById(id),GROUPS={emp:['Empresários','💼'],mil:['Militares','🛡️'],sind:['Trabalhadores','🧰'],sau:['Serviço público','🏥'],uni:['Academia','🎓'],jovens:['Jovens','📱'],aposentados:['Aposentados','🧓'],ambientais:['Ambientalistas','🌱'],conservadores:['Conservadores','🏛️'],progressistas:['Progressistas','✊']};
  const state={pending:1,lastQueuedDay:0,lastShownDay:-999,deck:[],usedTitles:[],toastTimer:null};
  try{const saved=JSON.parse(localStorage.getItem('estadoMaior.v25.briefings')||'null');if(saved)Object.assign(state,{pending:saved.pending??1,lastQueuedDay:saved.lastQueuedDay||0,lastShownDay:saved.lastShownDay||-999,usedTitles:saved.usedTitles||[]});}catch(e){}
  const shuffle=a=>a.slice().sort(()=>Math.random()-.5);
  function refillDeck(){state.deck=shuffle(['society','cabinet','economy','election','memory','story']);}
  function nextCategory(){if(!state.deck.length)refillDeck();return state.deck.shift();}
  function remember(type,text,impact=0){window.EMDepth?.remember?.(type,text,impact,PLAYER?.nome||'Brasil',540);}
  function adjustGroups(changes){if(!PLAYER)return;Object.entries(changes).forEach(([k,v])=>PLAYER.grupos[k]=clamp((PLAYER.grupos[k]??50)+v,0,100));}
  function costOrWarn(cost,label){if(PLAYER.caixa>=cost)return true;addBulletin('⚠️',label,`O Tesouro precisa de ${money(cost)}, mas não possui recursos suficientes.`,'warn','results');return false;}
  function uniqueTitle(options){const available=options.filter(x=>!state.usedTitles.includes(x));const title=pick(available.length?available:options);state.usedTitles=[title,...state.usedTitles.filter(x=>x!==title)].slice(0,12);return title;}

  function societyBrief(){
    const entries=Object.keys(GROUPS).map(k=>[k,PLAYER.grupos[k]??50]).sort((a,b)=>a[1]-b[1]),[key,value]=entries[0],[name,icon]=GROUPS[key],cost=PLAYER.pib*.009;
    return{ico:icon,title:uniqueTitle(['A base começa a se mover','Uma maioria pode escapar','O grupo que o governo não ouviu']),desc:`${name} registram apenas ${Math.round(value)}% de apoio. Lideranças cobram acesso ao governo e ameaçam transformar insatisfação em oposição organizada.`,choices:[
      {l:'Abrir uma mesa de negociação',t:'Ouvir demandas e construir compromissos.',efeito:'−1 influência · apoio do grupo +12 · legitimidade +3',go:m=>{if(influence<1)return addBulletin('⚠️','Sem influência','A negociação não avançou.','warn','results');influence--;adjustGroups({[key]:12});m.legitimidade+=3;m.aprovacao+=1;remember('sociedade',`${name} foram recebidos pelo governo.`,4);},msg:`Negociação com ${name}`},
      {l:'Criar uma resposta direcionada',t:'Usar orçamento para atender a principal reivindicação.',efeito:`−${money(cost)} · apoio +16 · aprovação +2`,go:m=>{if(!costOrWarn(cost,'Programa não financiado'))return;m.caixa-=cost;adjustGroups({[key]:16});m.aprovacao+=2;remember('sociedade',`Um programa foi direcionado a ${name}.`,5);},msg:'Programa social direcionado'},
      {l:'Confrontar publicamente',t:'Recusar pressão e demonstrar autoridade.',efeito:'Estabilidade +3 · apoio −10 · legitimidade −4',go:m=>{adjustGroups({[key]:-10,conservadores:3});m.estabilidade+=3;m.legitimidade-=4;remember('sociedade',`O governo confrontou ${name}.`,-6);},msg:'Confronto com grupo social'}]};
  }
  function cabinetBrief(){
    const cabinet=window.EMStrategy?.cabinet||[],minister=cabinet.slice().sort((a,b)=>(b.scandal||0)-(a.scandal||0)||(b.ambition||45)-(a.ambition||45))[0]||cabinet[0];if(!minister)return societyBrief();
    minister.ambition??=45;minister.popularity??=clamp(minister.skill*.55+minister.loyalty*.25+10,25,85);const i=cabinet.indexOf(minister),risk=minister.scandal?'documentos ligam o ministério a contratos suspeitos':minister.ambition>70?'aliados dizem que o ministro prepara um projeto político próprio':'o desempenho da pasta virou assunto dentro da coalizão';
    return{ico:'🏛️',title:uniqueTitle(['A reunião que terminou sem aplausos','Um ministro grande demais','O gabinete pede uma decisão']),desc:`${minister.name}, titular de ${minister.role}: ${risk}. Competência ${Math.round(minister.skill)}, lealdade ${Math.round(minister.loyalty)} e popularidade ${Math.round(minister.popularity)}.`,choices:[
      {l:'Dar protagonismo ao ministro',t:'Usar sua popularidade a favor do governo.',efeito:'Aprovação +2 · lealdade +5 · ambição +8',go:m=>{minister.popularity=clamp(minister.popularity+6,0,100);minister.loyalty+=5;minister.ambition+=8;m.aprovacao+=2;remember('gabinete',`${minister.name} ganhou protagonismo nacional.`,2);},msg:'Ministro fortalecido'},
      {l:'Abrir investigação interna',t:'Auditar contratos, equipe e decisões da pasta.',efeito:'Legitimidade +4 · lealdade −9 · risco de ruptura',go:m=>{minister.scandal=0;minister.loyalty-=9;m.legitimidade+=4;remember('gabinete',`${minister.name} foi investigado pelo próprio governo.`,3);},msg:'Investigação no gabinete'},
      {l:'Substituir imediatamente',t:'Encerrar a crise e nomear uma nova liderança.',efeito:'−2 influência · novo ministro · base dividida',go:m=>{if(influence<2)return addBulletin('⚠️','Troca bloqueada','A substituição exige 2 de influência.','warn','results');influence-=2;const names=['Ana Torres','Miguel Sampaio','Beatriz Lima','Daniel Rocha','Sofia Azevedo','Ravi Monteiro','Laura Nascimento'];minister.name=names[(i+dia)%names.length];minister.skill=58+Math.floor(Math.random()*28);minister.loyalty=70;minister.popularity=44;minister.ambition=34;minister.scandal=0;m.legitimidade+=1;remember('gabinete',`O titular de ${minister.role} foi substituído.`,-1);},msg:'Reforma ministerial'}]};
  }
  function economyBrief(){
    const commodities=window.EMStrategy?.commodities||{},stressed=Object.entries(commodities).sort((a,b)=>b[1]-a[1])[0]||['energia',100],[resource,index]=stressed,debt=PLAYER.divida/PLAYER.pib*100,cost=PLAYER.pib*.018;
    return{ico:'📊',title:uniqueTitle(['A conta chegou ao gabinete','Mercados testam o governo','O orçamento não aceita discursos']),desc:`${resource.toUpperCase()} está no índice ${Math.round(index)} e a dívida alcança ${Math.round(debt)}% do PIB. Empresas, famílias e Tesouro pressionam por respostas diferentes.`,choices:[
      {l:'Pacote de proteção econômica',t:'Subsidiar setores e evitar uma desaceleração.',efeito:`−${money(cost)} · aprovação +5 · estabilidade +3`,go:m=>{if(!costOrWarn(cost,'Pacote sem recursos'))return;m.caixa-=cost;m.aprovacao+=5;m.estabilidade+=3;commodities[resource]=Math.max(55,index-8);remember('economia',`O governo protegeu a economia durante a alta de ${resource}.`,3);},msg:'Pacote econômico lançado'},
      {l:'Ajuste fiscal imediato',t:'Conter gastos e recuperar confiança financeira.',efeito:'Caixa +2% PIB · aprovação −6 · dívida reduzida',go:m=>{m.caixa+=m.pib*.02;m.divida*=.975;m.aprovacao-=6;m.estabilidade-=2;remember('economia','O governo escolheu ajuste fiscal em meio à pressão.',-2);},msg:'Ajuste fiscal anunciado'},
      {l:'Investimento estratégico',t:'Atacar a causa com tecnologia e infraestrutura.',efeito:`−${money(cost*.75)} · ciência +5 · PIB +1,2%`,go:m=>{if(!costOrWarn(cost*.75,'Investimento adiado'))return;m.caixa-=cost*.75;m.ciencia+=5;m.pib*=1.012;commodities[resource]=Math.max(55,index-5);remember('economia',`Investimento estratégico reduziu dependência de ${resource}.`,5);},msg:'Investimento estratégico'}]};
  }
  function electionBrief(){
    const opposition=clamp(100-PLAYER.aprovacao+(PLAYER.oposicao||20)*.18,18,78),lead=Math.round(PLAYER.aprovacao-opposition),cost=PLAYER.pib*.007;
    return{ico:'🗳️',title:uniqueTitle(['A eleição entrou no gabinete','A rua começou a votar','Uma pesquisa muda o clima político']),desc:`O governo aparece com ${Math.round(PLAYER.aprovacao)}% e a oposição com ${Math.round(opposition)}%. ${lead>=0?`A vantagem é de ${lead} pontos, mas ainda pode desaparecer.`:`A oposição lidera por ${Math.abs(lead)} pontos.`}`,choices:[
      {l:'Mobilizar a base',t:'Atos nacionais com movimentos aliados.',efeito:'−1 ação · aprovação +3 · trabalhadores e jovens +4',go:m=>{if(cp<1)return addBulletin('⚠️','Sem ação política','A mobilização foi cancelada.','warn','results');cp--;m.aprovacao+=3;adjustGroups({sind:4,jovens:4});remember('eleição','O governo mobilizou sua base nacional.',3);},msg:'Base mobilizada'},
      {l:'Buscar eleitores de centro',t:'Moderar o discurso e negociar compromissos.',efeito:'−2 influência · legitimidade +4 · coalizão amplia',go:m=>{if(influence<2)return addBulletin('⚠️','Sem influência','A articulação não aconteceu.','warn','results');influence-=2;m.legitimidade+=4;adjustGroups({emp:3,uni:3,conservadores:2,progressistas:2});remember('eleição','A campanha buscou uma coalizão de centro.',4);},msg:'Campanha moderada'},
      {l:'Campanha nacional de comunicação',t:'Dominar rádio, TV e redes durante a semana.',efeito:`−${money(cost)} · aprovação +4 · legitimidade −1`,go:m=>{if(!costOrWarn(cost,'Campanha sem verba'))return;m.caixa-=cost;m.aprovacao+=4;m.legitimidade-=1;remember('eleição','Uma campanha de comunicação dominou o debate.',1);},msg:'Campanha de comunicação'}]};
  }
  function memoryBrief(){
    const memories=window.EMDepth?.memory||[],mem=memories.find(m=>m.expires>dia)||memories[0];if(!mem)return storyBrief();const positive=(mem.impact||0)>=0;
    return{ico:'📚',title:uniqueTitle(['O passado voltou à mesa','Uma promessa ainda cobra resposta','O país não esqueceu']),desc:`Assessores recuperam uma decisão do dia ${mem.day}: “${mem.text}”. ${positive?'Aliados querem transformar o episódio em legado.':'Críticos usam essa memória para questionar a coerência do governo.'}`,choices:[
      {l:'Assumir essa memória',t:'Defender publicamente a decisão e suas consequências.',efeito:`Legitimidade ${positive?'+4':'−2'} · aprovação ${positive?'+2':'−1'}`,go:m=>{m.legitimidade+=positive?4:-2;m.aprovacao+=positive?2:-1;mem.expires+=240;remember('memória',`O governo reafirmou: ${mem.text}`,positive?4:-2);},msg:'Memória reafirmada'},
      {l:'Reinterpretar a decisão',t:'Apresentar uma nova leitura e corrigir parte do rumo.',efeito:'−1 influência · reduz efeito negativo · estabilidade +2',go:m=>{if(influence<1)return addBulletin('⚠️','Sem articulação','A mudança de narrativa fracassou.','warn','results');influence--;mem.impact=Math.max(-1,(mem.impact||0)+3);m.estabilidade+=2;remember('memória',`O governo reinterpretou uma decisão anterior.`,1);},msg:'Rumo reinterpretado'},
      {l:'Encerrar o assunto',t:'Evitar alimentar o debate e olhar para frente.',efeito:'Assunto expira · críticos ou aliados reagem',go:m=>{mem.expires=dia;m.aprovacao+=positive?-2:1;m.legitimidade+=positive?-1:1;},msg:'Assunto encerrado'}]};
  }
  function storyBrief(){
    const active=(window.EMDepth?.stories||[]).find(s=>s.status==='active'&&s.awaiting)||(window.EMDepth?.stories||[]).find(s=>s.status==='active'),title=active?.title||uniqueTitle(['Uma crise sem dono','O relatório que ninguém queria assinar','A madrugada no Palácio']),detail=active?.history?.at(-1)||'Governadores, imprensa e aliados apresentam versões diferentes de uma crise que cresce fora dos holofotes.';
    return{ico:active?.icon||'📜',title,desc:`${detail} O gabinete precisa escolher um desfecho antes que a situação seja definida por outros atores.`,choices:[
      {l:'Negociar uma saída',t:'Construir acordo e dividir responsabilidades.',efeito:'Legitimidade +6 · diplomacia +3 · tensão −3',go:m=>{m.legitimidade+=6;m.diplo+=3;m.aprovacao+=2;addTension(-3,'O governo construiu uma saída negociada.');if(active){active.status='resolved';active.awaiting=false;active.outcome='Saída negociada';active.resolved=dia;}remember('história',`${title}: saída negociada.`,7);},msg:'Crise negociada'},
      {l:'Financiar uma solução rápida',t:'Mobilizar orçamento para encerrar o problema.',efeito:`−${money(PLAYER.pib*.012)} · estabilidade +5 · aprovação +3`,go:m=>{const cost=m.pib*.012;if(!costOrWarn(cost,'Solução sem orçamento'))return;m.caixa-=cost;m.estabilidade+=5;m.aprovacao+=3;if(active){active.status='resolved';active.awaiting=false;active.outcome='Resposta financiada';active.resolved=dia;}remember('história',`${title}: resposta emergencial financiada.`,3);},msg:'Resposta emergencial'},
      {l:'Impor autoridade',t:'Encerrar o impasse com uma decisão unilateral.',efeito:'Estabilidade +7 · legitimidade −8 · grupos divididos',go:m=>{m.estabilidade+=7;m.legitimidade-=8;m.aprovacao-=3;adjustGroups({mil:6,conservadores:5,progressistas:-9,jovens:-6});addTension(4,'Uma resposta dura encerrou o impasse.');if(active){active.status='resolved';active.awaiting=false;active.outcome='Autoridade imposta';active.resolved=dia;}remember('história',`${title}: autoridade imposta.`,-8);},msg:'Autoridade imposta'}]};
  }
  const briefingBuilders={society:societyBrief,cabinet:cabinetBrief,economy:economyBrief,election:electionBrief,memory:memoryBrief,story:storyBrief};

  function save(){if(!PLAYER)return;localStorage.setItem('estadoMaior.v25.briefings',JSON.stringify({pending:state.pending,lastQueuedDay:state.lastQueuedDay,lastShownDay:state.lastShownDay,usedTitles:state.usedTitles}));}
  function showToast(){let toast=$id('governmentBriefToastV25');toast.classList.add('on');clearTimeout(state.toastTimer);state.toastTimer=setTimeout(()=>toast.classList.remove('on'),4200);}
  function updateBriefingBadge(){
    const button=$id('govOpen'),mobile=document.querySelector('[data-v23-mobile="government"]');[button,mobile].forEach(b=>b?.classList.toggle('briefingPending',state.pending>0));
    document.querySelectorAll('.governmentRailBadge').forEach(x=>{x.textContent=state.pending;x.classList.toggle('zero',state.pending===0);});if(button&&!button.querySelector('.governmentRailBadge'))button.insertAdjacentHTML('beforeend',`<span class="governmentRailBadge ${state.pending===0?'zero':''}">${state.pending}</span>`);
  }
  function openBriefing(){
    if(!PLAYER)return;if($id('popup')?.classList.contains('on')){showToast();return;}const category=nextCategory(),brief=briefingBuilders[category]();state.pending=Math.max(0,state.pending-1);state.lastShownDay=dia;updateBriefingBadge();save();
    const choices=brief.choices.map(c=>({...c,go:m=>{c.go(m);refresh();setTimeout(()=>{if(dia-state.lastQueuedDay>70&&state.pending===0){state.pending=1;updateBriefingBadge();}},200);}}));showPopup(brief.ico,brief.title,brief.desc,choices);
  }
  function queueBriefing(){if(!PLAYER||state.pending>=3)return;state.pending++;state.lastQueuedDay=dia;updateBriefingBadge();showToast();addBulletin('♟','Briefing aguarda decisão','Sociedade, gabinete, eleição ou economia exigem atenção do governo.','warn','general');save();}

  /* Substitui o antigo conjunto de três decisões políticas repetidas. */
  gerarDecisaoPolitica=function(){queueBriefing();};

  /* Remove os antigos listeners da sala e transforma o botão em evento. */
  const oldGov=$id('govOpen');if(oldGov){const fresh=oldGov.cloneNode(true);oldGov.replaceWith(fresh);fresh.title='Abrir próximo briefing do governo';const label=fresh.querySelector('b');if(label)label.textContent='BRIEFING';fresh.onclick=openBriefing;}
  const oldMobileGov=document.querySelector('[data-v23-mobile="government"]');if(oldMobileGov){const fresh=oldMobileGov.cloneNode(true);oldMobileGov.replaceWith(fresh);fresh.innerHTML='<span>♟</span>BRIEFING';fresh.onclick=()=>{document.querySelectorAll('.mobileNavBtn').forEach(x=>x.classList.toggle('active',x===fresh));closeMobilePanels();document.body.classList.remove('mobile-panel-open');openBriefing();};}
  $id('governmentRoom')?.classList.remove('on');
  document.body.insertAdjacentHTML('beforeend','<div id="governmentBriefToastV25" class="governmentBriefToast"><small>NOVO BRIEFING DE GOVERNO</small><strong>Uma decisão está aguardando você</strong><span>Abra BRIEFING no menu. As categorias se alternam para evitar repetição.</span></div>');

  /* Central Estratégica destacada e resumida. */
  const strategyButton=$id('strategyOpen');if(strategyButton){const label=strategyButton.querySelector('b');if(label)label.textContent='ESTRATÉGIA';strategyButton.insertAdjacentHTML('beforeend','<span class="strategyRailBadge">0</span>');}
  const head=document.querySelector('#strategyPanel .strategyHead');if(head&&!$id('strategyPriorityV25'))head.insertAdjacentHTML('afterend','<div id="strategyPriorityV25"><div><small>CENTRAL DE CONTROLE</small><strong id="strategyPriorityTitle">Calculando prioridades...</strong><span id="strategyPriorityText">Conflitos, projetos e mercados reunidos em um só lugar.</span></div><div class="strategyPriorityScore" id="strategyPriorityScore">0</div></div>');
  document.body.insertAdjacentHTML('beforeend','<button id="strategyCommandV25" type="button"><span class="strategyCommandIcon">◈</span><span class="strategyCommandText"><b>CENTRAL ESTRATÉGICA</b><span id="strategyCommandSummary">Abrir conflitos, blocos, projetos e inteligência</span></span><span id="strategyCommandCount">0</span></button>');
  function strategyUrgency(){const conflicts=(window.EMStrategy?.conflicts||[]).filter(c=>c.intensity>=65).length,crises=(window.EMCrisis?.crises||[]).filter(c=>!c.contained).length,projects=(window.EMStrategy?.projects||[]).filter(p=>!p.done).length,scarce=Object.values(window.EMStrategy?.commodities||{}).filter(v=>v>=120).length;return{conflicts,crises,projects,scarce,total:conflicts+crises+scarce};}
  function updateStrategy(){const u=strategyUrgency(),risk=Math.max(window.EMCrisis?.worldDoom?.()||0,worldTension||0),title=u.total?`${u.total} prioridade${u.total>1?'s':''} exigem atenção`:'Cenário sob controle',text=`${u.conflicts} conflitos críticos · ${u.crises} crises em expansão · ${u.projects} projetos ativos · ${u.scarce} mercados sob pressão`;$id('strategyPriorityTitle').textContent=title;$id('strategyPriorityText').textContent=text;$id('strategyPriorityScore').textContent=Math.round(risk);$id('strategyCommandSummary').textContent=text;$id('strategyCommandCount').textContent=u.total;document.querySelector('.strategyRailBadge').textContent=u.total;}
  function openStrategy(){if(!$id('strategyPanel')?.classList.contains('on'))strategyButton?.click();document.querySelector('.strategyTabs [data-st="world"]')?.click();updateStrategy();}
  $id('strategyCommandV25').onclick=openStrategy;
  document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,button'))return;if(e.key.toLowerCase()==='e')openStrategy();if(e.key.toLowerCase()==='g')openBriefing();});

  const startBase=startGame;startGame=function(n){const r=startBase(n);state.lastQueuedDay=dia;state.pending=Math.max(1,state.pending);updateBriefingBadge();updateStrategy();setTimeout(()=>{if(localStorage.getItem('EM.tutorialSeen'))showToast();},900);return r;};
  const tickBase=tick;tick=function(dt){const before=dia,r=tickBase(dt);if(PLAYER&&dia!==before&&dia-state.lastQueuedDay>=115){queueBriefing();}return r;};
  const refreshBase=refresh;refresh=function(){const r=refreshBase();updateStrategy();updateBriefingBadge();return r;};
  updateBriefingBadge();updateStrategy();setInterval(()=>{updateStrategy();updateBriefingBadge();save();},6000);window.addEventListener('beforeunload',save);
  window.EMBriefings={open:openBriefing,queue:queueBriefing,state};
})();
